console.log("Olá mundo")
alert("Olá mundo")
var nome="Thais"
nome = 22
 var vetor = [1,2,3,4,5,6,7,8,9]
 vetor[2]
 var objeto={}
 pessoa["nome"] ="Teste"


 const idade=1 
 alert("Idade")

 if(idade >=18 ) {
   alert("Maior de idade") 
 }else if (idade>=18){
    alert("Jovem adolecente")
}else{
    alert("Menor de Idade :")
 
}



let contador =1
while(contador <= limite) {
    alert("Limite "+contador)
    contador ++
}

let contador =1 
for(contador =1 ;contador <=limite;contador ++){
    alert("Contador"+contador)
}
function soma(int1 , int2){
    return int1 +int2
}
 let resultado = soma(1,2)

 alert("Soma é "+ resultado)
